import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";
import Footer from "@/components/Footer/Footer";


const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "L'atelier Burgundy",
    description: "Generated by create next app",
    icons: {
        icon: [
            {url: '/favicon.svg', type: 'image/svg+xml'}
        ]
    }
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}

